"""
power_bus
------------
Power Bus subsystem for the ORCA Digital Twin.

The Power Bus connects the Solar Model, Battery Model,
and Payload Model by computing the spacecraft's electrical
power balance every simulation step.
"""

from .config import (
    ESSENTIAL_BUS_POWER,
    BUS_VOLTAGE,
)


class PowerBusModel:
    """
    Simplified spacecraft Electrical Power System (EPS).
    """

    def __init__(self):

        # Configuration
        self.essential_bus_power = ESSENTIAL_BUS_POWER
        self.bus_voltage = BUS_VOLTAGE
        self.bus_efficiency = 0.95
        self.minimum_soc = 20.0

        # State Variables
        self.total_load = 0.0
        self.net_power = 0.0
        self.bus_status = "INITIALIZING"

    def update(
        self,
        solar_power: float,
        payload_power: float,
        battery_soc: float,
    ):
        """
        Update spacecraft power balance.

        Parameters
        ----------
        solar_power : float
            Power generated by solar array (W)

        payload_power : float
            Total payload consumption (W)

        battery_soc : float
            Battery State of Charge (%)
        """

        # Include spacecraft housekeeping load
        self.total_load = (
            self.essential_bus_power
            + (payload_power / self.bus_efficiency)
        )

        # Net spacecraft power
        self.net_power = solar_power - self.total_load

        # Bus operating state
        if self.net_power >= 0:

            self.bus_status = "NOMINAL_CHARGE"

        elif battery_soc > self.minimum_soc:

            self.bus_status = "NOMINAL_DISCHARGE"

        else:

            self.bus_status = "CRITICAL_DEFICIT"

        return self.net_power

    def get_net_power(self):
        return round(self.net_power, 2)

    def get_total_load(self):
        return round(self.total_load, 2)

    def get_bus_status(self):
        return self.bus_status

    def get_power_balance(self):
        """
        Returns generation vs consumption.
        """

        return {
            "generation": round(
                self.net_power + self.total_load,
                2,
            ),
            "consumption": round(
                self.total_load,
                2,
            ),
        }

    def get_state(self):
        """
        Return Power Bus telemetry.
        """

        return {
            "total_load": self.get_total_load(),
            "net_power": self.get_net_power(),
            "bus_status": self.get_bus_status(),
            "power_balance": self.get_power_balance(),
        }