"""
solar_model
----------------
Solar Power subsystem for the ORCA Digital Twin.

This model estimates electrical power generated by the spacecraft's
solar arrays based on the current orbital position.
"""

import math

from .config import (
    SOLAR_MAX_POWER,
    ORBIT_PERIOD,
    SUNLIGHT_DURATION,
)


class SolarModel:
    """
    Simplified Solar Power Model.

    Simulates power generation during the sunlit portion of the orbit
    and zero generation during eclipse.
    """

    def __init__(self):
        # Configuration
        self.max_power = SOLAR_MAX_POWER
        self.orbit_period = ORBIT_PERIOD
        self.sunlight_duration = SUNLIGHT_DURATION

        # State Variables
        self.power = 0.0
        self.orbit_phase = "UNKNOWN"

    def update(self, orbit_time):
        """
        Update solar power generation.

        Parameters
        ----------
        orbit_time : float
            Elapsed simulation time (seconds).

        Returns
        -------
        float
            Generated solar power (Watts).
        """

        # Position within one orbit
        t_pos = orbit_time % self.orbit_period

        # Eclipse
        if t_pos >= self.sunlight_duration:
            self.orbit_phase = "ECLIPSE"
            self.power = 0.0

        # Sunlight
        else:
            self.orbit_phase = "SUNLIGHT"

            # Smooth solar power profile
            angle = math.pi * t_pos / self.sunlight_duration

            self.power = self.max_power * math.sin(angle)

        return self.power

    def get_power(self):
        """Return current solar power."""
        return round(self.power, 2)

    def get_orbit_phase(self):
        """Return current orbit phase."""
        return self.orbit_phase

    def get_state(self):
        """
        Return solar telemetry.
        """

        return {
            "solar_power": self.get_power(),
            "orbit_phase": self.get_orbit_phase(),
        }